"""Step 8 (optional) - upload the exported model dir to the HuggingFace Hub.

Requires a write token (``huggingface-cli login`` or the ``HF_TOKEN`` env var).

    python -m training.push_to_hub --config training/configs/telugu.yaml \
        --repo-id your-username/chatterbox-telugu

The export dir already contains a model card (README.md) generated by
merge_and_export. Large files (s3gen.pt, the T3 weights) are uploaded via LFS
automatically.
"""
from __future__ import annotations

import argparse
import os
from pathlib import Path

from training.common import load_config


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--config", required=True)
    p.add_argument("--model-dir", default=None, help="defaults to cfg.paths.export")
    p.add_argument("--repo-id", default=None, help="defaults to cfg.upload.repo_id")
    p.add_argument("--private", action="store_true", help="force private (else uses cfg.upload.private)")
    p.add_argument("--token", default=None, help="HF write token (else uses HF_TOKEN env)")
    args = p.parse_args()

    cfg = load_config(args.config)
    from huggingface_hub import HfApi

    model_dir = Path(args.model_dir or cfg.paths.export)
    if not (model_dir / "config.json").exists():
        raise SystemExit(f"{model_dir} doesn't look like an export dir. Run merge_and_export first.")

    repo_id = args.repo_id or cfg.upload.repo_id
    if not repo_id:
        raise SystemExit("Set --repo-id or cfg.upload.repo_id (e.g. your-username/chatterbox-telugu).")

    token = args.token or os.getenv("HF_TOKEN")
    if not token:
        raise SystemExit("No HF token. Run `huggingface-cli login` or set HF_TOKEN.")

    private = bool(args.private or cfg.upload.private)
    # The export dir can accumulate HF-cache cruft (a `models--*` snapshot dir, `.locks/`,
    # `CACHEDIR.TAG`) and generated demo audio (`samples/`). Upload ONLY the model itself.
    # fnmatch `*` crosses `/`, so `models--*` covers the whole nested cache tree.
    ignore_patterns = [
        "samples*",        # generated demo WAVs
        "models--*",       # huggingface_hub cache snapshot dir
        ".locks*",         # cache lock dir
        "*.lock",
        "CACHEDIR.TAG",    # cache-dir marker
        ".cache*",
    ]
    api = HfApi(token=token)
    api.create_repo(repo_id=repo_id, repo_type="model", private=private, exist_ok=True)
    print(f"[push] uploading {model_dir} -> https://huggingface.co/{repo_id} (private={private})")
    api.upload_folder(
        folder_path=str(model_dir),
        repo_id=repo_id,
        repo_type="model",
        commit_message=f"Add Chatterbox {cfg.language_name} ({cfg.language}) fine-tune",
        ignore_patterns=ignore_patterns,
    )
    print(f"[push] done -> https://huggingface.co/{repo_id}")


if __name__ == "__main__":
    main()
